# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: morecore
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: hm-api
service: hm-service

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  memorySize: 128
  timeout: 10
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
  apiGateway:
    shouldStartNameWithService: true
    restApi:
      role:
        statements:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
  # environment:
  #   TOKEN_SECRET_KEY: ${env:TOKEN_SECRET_KEY}
  #   DB_USERNAME: ${env:DB_USERNAME}
  #   DB_PASSWORD: ${env:DB_PASSWORD}
  #   DB_NAME: ${env:DB_NAME}
  #   SQL_HOST: ${env:SQL_HOST}
  #   SQL_USER: ${env:SQL_USER}
  #   SQL_PASSWORD: ${env:SQL_PASSWORD}
  #   DB_TYPE: ${env:DB_TYPE}

functions:
  api:
    handler: dist/handler.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

# package:
#   individually: true
#   excludeDevDependencies: true

plugins:
  - serverless-offline