# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: morecore
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: hm-api
service: hm-service

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  memorySize: 128
  timeout: 10

functions:
  api:
    handler: dist/handler.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
  # hello:
  #   handler: handler.hello
  #   events:
  #     - http:
  #         path: /hello
  #         method: get

# package:
#   individually: true
#   excludeDevDependencies: true

plugins:
  - serverless-offline