# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: morecore
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: hm-api
service: hm-service

package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  memorySize: 128
  timeout: 60
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
  apiGateway:
    shouldStartNameWithService: true

  # environment:
  #   TOKEN_SECRET_KEY: ${env:TOKEN_SECRET_KEY}
  #   DB_USERNAME: ${env:DB_USERNAME}
  #   DB_PASSWORD: ${env:DB_PASSWORD}
  #   DB_NAME: ${env:DB_NAME}
  #   SQL_HOST: ${env:SQL_HOST}
  #   SQL_USER: ${env:SQL_USER}
  #   SQL_PASSWORD: ${env:SQL_PASSWORD}
  #   DB_TYPE: ${env:DB_TYPE}

functions:
  api:
    handler: dist/handler.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'  # Permite todas las orígenes, ajusta según sea necesario.
            allowHeaders:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
            allowMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true

  hello:
    handler: dist/handler.hello
    events:
      - http:
          path: /hello-world
          method: ANY
          cors: 
            origin: '*'  # Permite todas las orígenes, ajusta según sea necesario.
            allowHeaders:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
            allowMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true

# package:
#   individually: true
#   excludeDevDependencies: true

plugins:
  - serverless-offline